services:
  redis:
    image: redis:8.6
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --databases ${REDIS_DATABASES}  --appendonly yes

  redis-insight:
    image: redis/redisinsight:latest
    profiles:
      - dev
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

volumes:
  redis_data:
  redisinsight_data:
  pg_dev:
  pgadmin_data: